Run job always

diff --git a/.github/workflows/beyond-doubt.yaml b/.github/workflows/beyond-doubt.yaml
--- a/.github/workflows/beyond-doubt.yaml
+++ b/.github/workflows/beyond-doubt.yaml
@@ -212,7 +212,7 @@ jobs:
     name: Stack reporting
     timeout-minutes: 5
     needs: [stack-testing]
-    if: ${{ !cancelled() && (needs.stack-testing.result == 'success' || needs.stack-testing.result == 'failure') }}
+    if: ${{ !cancelled() && (contains(needs.*.result, 'success') || contains(needs.*.result, 'failure')) }}
     runs-on: ubuntu-22.04
     permissions:
       checks: write
@@ -224,16 +224,20 @@ jobs:
         with:
           check_name: E2E test report
           report_paths: "artifacts/e2e-test-report-*/**/TEST-*.xml"
-          require_tests: "${{ needs.stack-testing.result == 'failure' }}"
           fail_on_failure: false
           job_summary: false
 
   everything-is-fine:
     name: Everything is fine
     needs: [stack-publishing, stack-reporting]
-    if: ${{ contains(needs.*.result, 'failure') }}
     runs-on: ubuntu-latest
+    if: ${{ always() }}
     steps:
-      - run: |
+      - if: ${{ contains(needs.*.result, 'failure') }}
+        run: |
           echo "::error::Something went wrong"
+          exit 1
+      - if: ${{ contains(needs.*.result, 'skipped')) }}
+        run: |
+          echo "::error::Something was skipped"
           exit 1
diff --git a/.github/workflows/sanity.yaml b/.github/workflows/sanity.yaml
--- a/.github/workflows/sanity.yaml
+++ b/.github/workflows/sanity.yaml
@@ -47,9 +47,14 @@ jobs:
   everything-is-fine:
     name: Everything is fine
     needs: [up-to-binaries]
-    if: ${{ contains(needs.*.result, 'failure') }}
     runs-on: ubuntu-latest
+    if: ${{ always() }}
     steps:
-      - run: |
+      - if: ${{ contains(needs.*.result, 'failure') }}
+        run: |
           echo "::error::Something went wrong"
+          exit 1
+      - if: ${{ contains(needs.*.result, 'skipped')) }}
+        run: |
+          echo "::error::Something was skipped"
           exit 1
